### ISSUE TITLE
dosnt work rih

### ISSUE THREAD

**Issue by treakiandroid** [JonasCz/save-for-offline#15]

**Comment by treakiandroid** [comment]
Dosnt work right, if i share an url woth this app i am getting an infinite notification, and some force closes:

```
build.board: herring
build.bootloader: I9020XXLC2
build.brand: Google
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: crespo
build.display: cm_crespo-userdebug 4.4.4 KTU84Q 5b8388ef7b test-keys
build.fingerprint: google/soju/crespo:4.1.2/JZO54K/485486:user/release-keys
build.hardware: herring
build.host: cyanogenmod
build.id: KTU84Q
build.manufacturer: Samsung
build.model: Nexus S
build.product: soju
build.radio: unknown
build.serial: 3334DB72EFC600EC
build.tags: test-keys
build.time: 1415771526000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: 5b8388ef7b
version.release: 4.4.4
version.sdk_int: 19

05-26 06:42:44.071 I/Timeline(19015): Timeline: Activity_launch_request id:jonas.tool.saveForOffline time:15857684
05-26 06:42:44.071 I/ActivityManager(398): START u0 {act=android.intent.action.SEND typ=text/plain flg=0x3000001 cmp=jonas.tool.saveForOffline/.AddActivity (has clip) (has extras)} from pid 19015
05-26 06:42:44.762 I/ActivityManager(398): Start proc jonas.tool.saveForOffline for activity jonas.tool.saveForOffline/.AddActivity: pid=24624 uid=10185 gids={50185, 3003, 1028, 1015}
05-26 06:42:45.274 D/ActivityThread(24624): handleBindApplication:jonas.tool.saveForOffline
05-26 06:42:50.059 I/ActivityManager(398): Process jonas.tool.saveForOffline (pid 24624) has died.
05-26 06:42:50.059 W/ActivityManager(398): Scheduling restart of crashed service jonas.tool.saveForOffline/.SaveService in 1000ms
05-26 06:43:40.501 I/Timeline(1157): Timeline: Activity_launch_request id:jonas.tool.saveForOffline time:15914116
05-26 06:43:40.505 I/ActivityManager(398): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=jonas.tool.saveForOffline/.MainActivity bnds=[339,288][438,401]} from pid 1157
05-26 06:43:40.977 I/ActivityManager(398): Start proc jonas.tool.saveForOffline for activity jonas.tool.saveForOffline/.MainActivity: pid=24858 uid=10185 gids={50185, 3003, 1028, 1015}
05-26 06:43:41.251 D/ActivityThread(24858): handleBindApplication:jonas.tool.saveForOffline
05-26 06:43:42.305 I/ActivityManager(398): Displayed jonas.tool.saveForOffline/.MainActivity: +1s416ms (total +57s560ms)
05-26 06:43:42.333 I/Timeline(398): Timeline: Activity_windows_visible id: ActivityRecord{42465c20 u0 jonas.tool.saveForOffline/.MainActivity t21} time:15915946
05-26 06:43:50.747 E/AndroidRuntime(24858): Process: jonas.tool.saveForOffline, PID: 24858
05-26 06:43:50.747 E/AndroidRuntime(24858): java.lang.RuntimeException: Unable to start service jonas.tool.saveForOffline.SaveService@41dbb418 with Intent { flg=0x10000000 cmp=jonas.tool.saveForOffline/.SaveService bnds=[96,608][480,680] (has extras) }: java.lang.NullPointerException
05-26 06:43:50.747 E/AndroidRuntime(24858):     at jonas.tool.saveForOffline.SaveService.onStartCommand(SaveService.java:113)
05-26 06:43:50.758 W/ActivityManager(398):   Force finishing activity jonas.tool.saveForOffline/.MainActivity
05-26 06:43:51.462 W/ActivityManager(398): Activity pause timeout for ActivityRecord{42465c20 u0 jonas.tool.saveForOffline/.MainActivity t21 f}
05-26 06:43:58.614 I/ActivityManager(398): Process jonas.tool.saveForOffline (pid 24858) has died.
05-26 06:43:58.614 W/ActivityManager(398): Scheduling restart of crashed service jonas.tool.saveForOffline/.SaveService in 29541ms
05-26 06:43:58.614 I/WindowState(398): WIN DEATH: Window{425a8ce8 u0 jonas.tool.saveForOffline/jonas.tool.saveForOffline.MainActivity}
05-26 06:44:28.188 I/ActivityManager(398): Start proc jonas.tool.saveForOffline for service jonas.tool.saveForOffline/.SaveService: pid=25179 uid=10185 gids={50185, 3003, 1028, 1015}
05-26 06:44:29.094 D/ActivityThread(25179): handleBindApplication:jonas.tool.saveForOffline
05-26 06:44:29.450 E/AndroidRuntime(25179): Process: jonas.tool.saveForOffline, PID: 25179
05-26 06:44:29.450 E/AndroidRuntime(25179): java.lang.RuntimeException: Unable to start service jonas.tool.saveForOffline.SaveService@41d62b88 with Intent { flg=0x10000000 cmp=jonas.tool.saveForOffline/.SaveService bnds=[96,608][480,680] (has extras) }: java.lang.NullPointerException
05-26 06:44:29.450 E/AndroidRuntime(25179):     at jonas.tool.saveForOffline.SaveService.onStartCommand(SaveService.java:113)
05-26 06:44:31.790 I/ActivityManager(398): Process jonas.tool.saveForOffline (pid 25179) has died.
05-26 06:44:31.790 W/ActivityManager(398): Service crashed 2 times, stopping: ServiceRecord{42773b70 u0 jonas.tool.saveForOffline/.SaveService}
```

Thanks for fixing

**Comment by JonasCz** [comment]
I will fix it.

**Comment by JonasCz** [comment]
Should be fixed now, let me know if it still crashes, and also the url it crashes on.
